language: node_js
node_js:
    - "6"
cache:
    directories:
        - node_modules
before_install:
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq chromium-browser
before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
script:
    - npm test
    - npm run webdriver-manager update
    - npm run protractor
    - npm build
sudo: required